name: ci

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          
      - name: install packages
        run: npm ci
        
      - name: run lint
        run: npm run lint
  
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          
      - name: install packages
        run: npm ci
        
      - name: run test
        run: npm run test
        
      - name: codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
