name: npm_publish

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'publish@') }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci
      - run: npm test
      - run: npm run build

      - uses: mmarchini-oss/npm-otp-publish@v0
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_actor: ${{ github.actor }}
